DataModeling :
    SupervisedLearning :
        Convex : False
        DecisionTree : False
        LinearRegression : False
        LogisticRegression :
        MultinomialLogisticRegression : False
        NaiveBayesClassification : False
        RandomForest : False
        SupportVectorMachines : False
        GeneralCV : False
    UnsupervisedLearning :
        kMeansClustering : False
        AssociationRules : False
        ParallelLatentDirichletAllocation : False
InferentialStatistics :
    HypothesisTests : False
Common :
